# IBM POC adov2-model sample   WIP
###
trigger:
  branches:
    include: 
      - '*' 
  tags:
    include: 
      - '*'

pool:
  name: self-hosted 
  
variables:      
  MyWorkDir:    "/tmp/adov2-workdir/$(System.TeamProject)_$(Build.BuildNumber)"
  MyWorkSpace:  "zdevops"
  MyRepo:       "?REPO_SSH_URL"
  MyApp:        "source"   
  MyEndPoint:   "?ADO_Agent_TEST_LPAR?"
jobs:
- job: Build_and_Publish 
  steps:          
  - checkout: none  
  - task: SSH@0
    displayName: Clone
    inputs:
      # new ado used poc* endpoint 
      sshEndpoint: $(MyEndPoint) 
      commands: |
        . /etc/profile && $ZDEVOPS_HOME/conf/scripts/clone.sh  $(MyWorkDir)  $(MyWorkSpace)  $(MyRepo)   $(Build.SourceBranch)

    

  - task: SSH@0
    displayName:  Build
    inputs:
      # pool name 
      sshEndpoint:  $(MyEndPoint)
      commands: |
        . /etc/profile &&  $ZDEVOPS_HOME/conf/scripts/build.sh   $(MyWorkDir)    $(MyWorkSpace)     $(MyApp)   source/cobol/datbatch.cbl 
      # $zScripts/ci/build.sh   $(MyWorkDir)    $(MyWorkSpace)     $(MyApp)  --impactBuild 
    

 



